version: "3"

services:
  nginx:
    image: course_nginx:ver_1
    build:
      context: .
      dockerfile: ./docker/nginx/dockerfile_build

#  php:
 #   image: course_php:ver_1
 #   build:
 #     context: .
 #     dockerfile: ./docker/php/dockerfile_build
